# This is a basic workflow to help you get started with Actions

name: Build Example Markata Blog in CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "*"
      # do not trigger ci when pushing gh-pages step
      - "!prod-markata"
    paths:
      - 'example-markata-blog/**'
      - '.github/workflows/ci-markata-blog.yml'
  pull_request:
    branches:
      - "main"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-markata-blog
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Set up Python 3.10
        with:
          python-version: '3.10'

      - name: install hatch
        run: pip install hatch

      - name: build with markata
        run: hatch run build

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          # you can choose the target branch of your choice
          target_branch: prod-markata
          build_dir: markout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-markata-blog
    env:
      BASE_VERSION: ${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_number }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # From https://docs.docker.com/build/ci/github-actions/examples/#share-built-image-between-jobs
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: ./example-markata-blog
          file: ./example-markata-blog/Dockerfile
          build-args: |
            BASE_VERSION=${{env.BASE_VERSION}}
          tags: |
            example-markata-blog-latest
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Run Docker Container
        run: |
          docker load --input /tmp/myimage.tar
          docker run --rm example-markata-blog-latest


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
