name: CI for Python Hello World

on:
  workflow_dispatch:
  schedule:
    # Run at 10 pm every day
    - cron: '0 22 * * *'
  push:
    branches: [ "*" ]
    paths:
      - 'python-hello-world/**'
      - '.github/workflows/ci-python-hello-world.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: See vars
        run: echo ${{ github.ref }}
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-hello-world
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: pre-commit
        uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-hello-world
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install hatch
        run: pip install hatch

      - name: pytest
        run: hatch run cov
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-hello-world
    steps:
      - uses: actions/checkout@v3

      - name: Build the Python Hello World Docker image
        run: docker build . --file ./Dockerfile --tag pypeaday/base-images:python-hello-world-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER --tag pypeaday/base-images:python-hello-world-$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER --tag pypeaday/base-images:python-hello-world-latest

      - name: Run Docker Container
        run: docker run python-hello-world-latest
  push:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
      - name: Push branch
        run: docker push pypeaday/base-images:python-hello-world-$GITHUB_REF_NAME-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
        if: ${{ github.ref == 'refs/heads/integration' }}
      - name: Push main tag
        run: docker push pypeaday/base-images:python-hello-world-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Push latest
        run: docker push pypeaday/base-images:python-hello-world-latest
        if: ${{ github.ref == 'refs/heads/main' }}
