name: CI for Python Hello World

on:
  workflow_dispatch:
  schedule:
    # Run at 10 pm every day
    - cron: '0 22 * * *'
  push:
    branches: [ "*" ]
    paths:
      - 'python-hello-world/**'
      - '.github/workflows/ci-python-hello-world.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: See vars
        run: echo ${{ github.ref }}
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-hello-world
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: pre-commit
        uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-hello-world
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install hatch
        run: pip install hatch

      - name: pytest
        run: hatch run cov
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-hello-world
    steps:
      # From https://docs.docker.com/build/ci/github-actions/examples/#share-built-image-between-jobs
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: ./python-hello-world
          build-args: |
            APP_VERSION=$GITHUB_REF_NAME-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
          tags: |
            "pypeaday/base-images:python-hello-world-$GITHUB_REF_NAME-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER"
            "pypeaday/base-images:python-hello-world-latest"
            "python-hello-world-latest"
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Run Docker Container
        run: docker run python-hello-world-latest
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
  push:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
      # From https://docs.docker.com/build/ci/github-actions/examples/#share-built-image-between-jobs
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # -
        # name: Login to Docker Hub
        # uses: docker/login-action@v2
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      - name: Push branch
        run: docker push pypeaday/base-images:python-hello-world-$GITHUB_REF_NAME-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
        if: ${{ github.ref == 'refs/heads/integration' }}
      - name: Push main tag
        run: docker push pypeaday/base-images:python-hello-world-$GITHUB_REF_NAME-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Push latest
        run: docker push pypeaday/base-images:python-hello-world-latest
        if: ${{ github.ref == 'refs/heads/main' }}
