name: CI for Base Images

on:
  workflow_dispatch:
  schedule:
    # Run at 10 pm every day
    - cron: '0 22 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Hello World Docker image
        if: contains(github.event.paths, '/hello-world/**')
        run: docker build ./hello-world --file ./hello-world/Dockerfile --tag hello-world:$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER --tag hello-world:latest

      - name: Run Docker Container
        if: contains(github.event.paths, '/hello-world/**')
        run: docker run python-hello-world

      - name: Build the Python Hello World Docker image
        if: contains(github.event.paths, '/python-hello-world/**')
        run: docker build ./python-hello-world --file ./python-hello-world/Dockerfile --tag python-hello-world:$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER --tag python-hello-world:latest

      - name: Run Docker Container
        if: contains(github.event.paths, '/python-hello-world/**')
        run: docker run python-hello-world
