name: Docker Image CI for Python Hello World

on:
  schedule:
    # Run at 10 pm every day
    - cron: '0 22 * * *'
  push:
    branches: [ "main" ]
    paths:
      - '/python-hello-world/**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: pre-commit
      uses: pre-commit/action@v3.0.0
    - name: Build the Docker image
      run: docker build ./python-hello-world --file ./python-hello-world/Dockerfile --tag python-hello-world:$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER --tag python-hello-world:latest
    - name: Run Docker Container
      run: docker run python-hello-world
